### ISSUE TITLE
Potential bug around getComputedStyle

### ISSUE THREAD

**Issue by richardwiggins** [CodyHouse/cd-responsive-sidebar-changelog#3] opened 2020-09-07 16:49 UTC
There seems to be a bug in this which is linked to [this issue](https://github.com/CodyHouse/cd-responsive-sidebar-changelog/issues/2) as well.

On Safari desktop and on mobile versions, `getComputedStyle` is firing the `static` version at small screen sizes when it should be firing `mobile`. Chrome is working correctly.

**Comment by claudia-romano** [comment] 2020-09-08 14:11
This appears to be a duplicate of https://github.com/CodyHouse/cd-responsive-sidebar-changelog/issues/2.

**Closed as completed by claudia-romano** 2020-09-08 14:11 UTC
